version: '2.2'
services:
    nginx:
        image: 'nginx:stable-alpine'
        volumes:
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/entrypoint.bash:/entrypoint.bash:ro'
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/ibexa_params.d:/etc/nginx/ibexa_params.d:ro'
        depends_on:
            - ibexa
        volumes_from:
            - 'ibexa:ro'
        entrypoint: /entrypoint.bash
        ports:
            - '${PROJECTPORTPREFIX}080:80'
            - '${PROJECTPORTPREFIX}081:81'
        environment:
            - PROJECTMAPPINGFOLDER
    ibexa:
        build: ./ibexa/
        volumes:
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/ibexa/php.ini:/usr/local/etc/php/php.ini:ro'
            - '${PROJECTCOMPOSEPATH}:${PROJECTMAPPINGFOLDER}:rw'
            - '${HOST_COMPOSER_CACHE_DIR}:${COMPOSER_CACHE_DIR}:rw'
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr:/ibexasolr:rw'
        shm_size: 754M
        environment:
            - COMPOSER_CACHE_DIR
            - PROJECTMAPPINGFOLDER
            - DEV_UID
            - DEV_GID
            - APP_CACHE_DIR
            - APP_LOG_DIR
            - RUNNING_ENV
            - XDEBUG_ENABLED=false
            # Uncomment two lines below for xdebug
            # - PHP_INI_SCAN_DIR=:/usr/local/etc/php/enable-xdebug
            # - XDEBUG_ENABLED=true
            - XDEBUG_CONFIG=client_host=172.22.0.1
            - PHP_IDE_CONFIG=serverName=ezplatform
            - PHP_IDE_KEY=XDEBUG_IDE_KEY
            - EZP_TEST_REST_HOST=nginx
            - DATABASE_PREFIXES=DATABASE
            - 'DATABASE_URL=mysql://root:ezplatform@db:3306/ibexa?serverVersion=mariadb-10.3.27'
            - APP_SECRET=SymfonyLaunchpad10Secret09Dev83ModeZ     # APP_SECRET must be at least 32 char long, JWT in page builder will break on shorter string
            - CUSTOM_CACHE_POOL=singleredis
            - CACHE_HOST=redis
            - CACHE_REDIS_PORT=6379
            - CACHE_POOL=cache.redis
            - 'CACHE_DSN=redis:6379'
            - SEARCH_ENGINE=solr
            - 'SOLR_DSN=http://solr:8983/solr'
            - SOLR_CORE=collection1
            - SESSION_HANDLER_ID=Ibexa\Bundle\Core\Session\Handler\NativeSessionHandler
            - 'SESSION_SAVE_PATH=tcp://redis:6379'
            - 'COMPOSER_MEMORY_LIMIT=-1'
            - 'MAILER_URL=smtp://mailcatcher:1025'
    db:
        image: 'mariadb:10.3'
        environment:
            - MYSQL_ROOT_PASSWORD=ezplatform
        volumes:
            - "db_data:/var/lib/mysql/"
        ports:
            - '${PROJECTPORTPREFIX}306:3306'
    varnish:
        image: plopix/docker-varnish6
        depends_on:
            - nginx
        volumes:
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/varnish/varnish.vcl:/etc/varnish/default.vcl:ro'
        ports:
            - '${PROJECTPORTPREFIX}082:80'
    solr-initializer:
        image: alpine
        restart: "no"
        entrypoint: |
            /bin/sh -c "chown -R 8983:8983 /ibexasolr"
        volumes:
            - "solr_data:/solr:rw"
    solr:
        image: 'solr:8.11.0'
        volumes:
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr/entrypoint.bash:/entrypoint.bash:ro'
            - 'solr_data:/opt/solr/data/:rw'
        volumes_from:
            - 'ibexa:rw'
        ports:
            - '${PROJECTPORTPREFIX}983:8983'
        entrypoint: /entrypoint.bash
        depends_on:
            - ibexa
            - solr-initializer
        environment:
            - DEV_UID
            - DEV_GID
            - PROJECTMAPPINGFOLDER
            - SOLR_CORES=collection1
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - '${PROJECTPORTPREFIX}180:1080'
    adminer:
        image: 'adminer:latest'
        ports:
            - '${PROJECTPORTPREFIX}084:8080'
    redis:
        image: 'redis:latest'
        depends_on:
            - ibexa
    redisadmin:
        image: 'rediscommander/redis-commander:latest'
        environment:
            - REDIS_HOST=redis
        ports:
            - '${PROJECTPORTPREFIX}083:8081'

volumes:
    db_data: ~
    solr_data: ~